# Generated by Django 4.2.11 on 2024-06-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('add', models.CharField(max_length=40)),
                ('sal', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
