# Generated by Django 4.2.11 on 2024-06-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empid', models.IntegerField()),
                ('Empname', models.CharField(max_length=255)),
                ('Empnum', models.IntegerField()),
                ('Empsal', models.FloatField()),
                ('Empadd', models.CharField(max_length=100)),
            ],
        ),
    ]
